### ISSUE TITLE
Images missing from blog post

### ISSUE THREAD

**Issue by gaborcsardi** [r-lgbtq/rainbowr-website#4]
https://rainbowr.netlify.app/posts/2024-06-15_rstartup is missing the SVG files, it seems:

<img width="1187" alt="Screenshot 2024-06-11 at 1 00 49 PM" src="https://github.com/r-lgbtq/rainbowr-website/assets/660288/5e4ce0e6-5eff-4fa6-9480-9a97bd0442c3">

**Comment by EllaKaye** [comment]
Hey @gaborcsardi. Thank you so much for spotting this and raising the issue. It should be fixed now.
